apiVersion: v1
kind: ConfigMap
metadata:
  name: gastro-api-config
  namespace: gastro-api
data:
  ASPNETCORE_ENVIRONMENT: "Production"

  # API must not execute EF migrations itself.
  ApplyMigrations: "false"