apiVersion: v1
kind: ConfigMap
metadata:
  name: gastro-api-config
  namespace: gastro-api

data:
  ASPNETCORE_ENVIRONMENT: "Production"
  ASPNETCORE_URLS: "http://+:8080"

  ApplyMigrations: "false"
