apiVersion: batch/v1
kind: Job
metadata:
  name: gastro-api-migrations
  namespace: gastro-api
  labels:
    app: gastro-api-migrations

spec:
  backoffLimit: 6

  template:
    metadata:
      labels:
        app: gastro-api-migrations

    spec:
      restartPolicy: OnFailure

      containers:
        - name: api
          image: ghcr.io/radixartem/gastro-api-k8s:942dd29
          imagePullPolicy: Always

          envFrom:
            - configMapRef:
                name: gastro-api-config
            - secretRef:
                name: gastro-api-secrets

          env:
            - name: ApplyMigrations
              value: "true"

            - name: MigrationOnly
              value: "true"

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"