apiVersion: v1
kind: Secret
metadata:
  name: gastro-api-secrets
  namespace: gastro-api
type: Opaque
stringData:
  POSTGRES_USER: "postgres"      # Измените на реальные значения
  POSTGRES_PASSWORD: "postgres"
  IMPORT_API_KEY: "9500b50ebfc1f176d79a089a6fe285bcd8a2b08403c46ca21360ff46dc6df777"
  GRAFANA_PASSWORD: "Yxcv123!@#"
  # Добавьте остальные секреты из .env.example